data:
  # resize dimensions to streamline model creation
  image_resize_dims:
    height: 256
    width: 256
  # ABSOLUTE path to data directory
  data_dir: /home/vsctsai/lightning-pose/lp-model
  # ABSOLUTE path to unlabeled videos' directory
  video_dir: /home/vsctsai/lightning-pose/lp-model/top_view/pppup
  # location of labels; this should be relative to `data_dir`
  csv_file: CollectedData.csv
  # downsample heatmaps - 2 | 3
  downsample_factor: 2
  # total number of keypoints
  num_keypoints: 7
  # keypoint names
  keypoint_names:
      - ear_left
      - tailbase
      - lateral_left
      - nose
      - center
      - lateral_right
      - ear_right
  # for mirrored setups with all keypoints defined in same csv file, define matching
  # columns for different keypoints (assumes x-y-x-y interleaving)
  # each list corresponds to a single view, so in the example below there are 2 views
  # keypoint 0 is from view 0 and matches up with keypoint 8 from view 2
  # columns that correspond to keypoints only labeled in a single view are omitted
  # this info is only used for the multiview pca loss
  mirrored_column_matches: null
  # list of indices of keypoints used for pca singleview loss (use order of labels file)
  columns_for_singleview_pca: [0, 1, 2, 3, 4, 5, 6]

training:
  # select from one of several predefined image/video augmentation pipelines
  # default- resizing only
  # dlc- imgaug pipeline implemented in DLC 2.0 package
  # dlc-top-down- curated subset of dlc augmentations with more conservative param settings
  imgaug: dlc
  # batch size of labeled data during training
  train_batch_size: 16
  # batch size of labeled data during validation
  val_batch_size: 48
  # batch size of labeled data during test
  test_batch_size: 48
  # fraction of labeled data used for training
  train_prob: 0.8
  # fraction of labeled data used for validation (remaining used for test)
  val_prob: 0.1
  # <=1 - fraction of total train frames (determined by `train_prob`) used for training
  # >1 - number of total train frames used for training
  train_frames: 1
  # number of gpus to train a single model
  num_gpus: 1
  # number of cpu workers for data loaders
  num_workers: 8
  # epochs over which to assess validation metrics for early stopping
  early_stop_patience: 3
  # epoch at which backbone network weights begin updating
  unfreezing_epoch: 20
  # dropout in final layers
  dropout_rate: 0.1
  # max training epochs; training may exit before due to early stopping
  min_epochs: 300
  max_epochs: 750
  # frequency to log training metrics (one step is one batch)
  log_every_n_steps: 10
  # frequency to log validation metrics
  check_val_every_n_epoch: 5
  # rng seed for labeled batches
  rng_seed_data_pt: 0
  # rng seed for weight initialization
  rng_seed_model_pt: 0
  # learning rate scheduler
  # multisteplr | [todo - reducelronplateau]
  lr_scheduler: multisteplr
  lr_scheduler_params:
    multisteplr:
      milestones: [150, 200, 250]
      gamma: 0.5

model:
  # list of unsupervised losses
  # "pca_singleview" | "pca_multiview" | "temporal" | "unimodal_mse" | "unimodal_kl"
  losses_to_use: ["pca_singleview", 'temporal']
  # backbone network:
  # resnet18 | resnet34 | resnet50 | *resnet101 | *resnet152 | resnet50_contrastive
  # trylowering batch size
  # resnet50_animal_apose | resnet50_animal_ap10k
  # resnet50_human_jhmdb | resnet50_human_res_rle | resnet50_human_top_res | resnet50_human_hand
  # efficientnet_b0 | efficientnet_b1 | efficientnet_b2
  # vit_b_sam | vit_h_sam
  backbone: resnet101
  # prediction mode: regression | heatmap | heatmap_mhcrnn (context)
  model_type: heatmap
  # which heatmap loss to use
  # mse | kl | js
  heatmap_loss_type: mse
  # directory name for model saving
  model_name: test
  # load model from checkpoint
  checkpoint: null

dali:
  general:
    seed: 123456

  base:
    train:
      sequence_length: 32
    predict:
      sequence_length: 96

  context:
    train:
      batch_size: 16
    predict:
      sequence_length: 96

losses:
  # loss = projection onto the discarded eigenvectors
  pca_multiview:
    # weight in front of PCA loss
    # 4, 5, 6
    log_weight: 5
    # predictions should lie within the low-d subspace spanned by these components
    components_to_keep: 3
    # absolute error (in pixels) below which pca loss is zeroed out; if null, an empirical
    # epsilon is computed using the labeled data
    epsilon: null
  # loss = projection onto the discarded eigenvectors
  pca_singleview:
    # weight in front of PCA loss
    log_weight: 5.0
    # predictions should lie within the low-d subspace spanned by components that describe this fraction of variance
    components_to_keep: 0.99
    # absolute error (in pixels) below which pca loss is zeroed out; if null, an empirical
    # epsilon is computed using the labeled data
    epsilon: null
  # loss = norm of distance between successive timepoints
  temporal:
    # weight in front of temporal loss
    log_weight: 5.0
    # for epsilon insensitive rectification
    # (in pixels; diffs below this are not penalized)
    epsilon: 20.0
    # nan removal value.
    # (in prob; heatmaps with max prob values are removed)
    prob_threshold: 0.05

eval:
  # predict? used in scripts/train_hydra.py
  predict_vids_after_training: True
  # str with an absolute path to a directory containing videos for prediction.
  test_videos_directory: /home/vsctsai/lightning-pose/lp-model/top_view/pppup
  # save labeled .mp4? used in scripts/train_hydra.py and scripts/predict_new_vids.py
  save_vids_after_training: true
  # matplotlib sequential or diverging colormap name for prediction visualization
  # sequential options: viridis, plasma, magma, inferno, cool, etc.
  # diverging options: RdBu, coolwarm, Spectral, etc.
  colormap: "cool"
  # confidence threshold for plotting a vid
  confidence_thresh_for_vid: 0.9

  # paths to the hydra config files in the output folder, OR absolute paths to such folders.
  # used in scripts/predict_new_vids.py and scripts/create_fiftyone_dataset.py
  hydra_paths: ["/home/vsctsai/lightning-pose/outputs/2025-01-30/09-27-48"]
#  hydra_paths: ["2025-01-30/00-01-25", "2025-01-29/08-42-14", "2025-01-30/09-27-48", "2025-01-29/16-23-30"]

  fiftyone:
    # will be the name of the dataset (Mongo DB) created by FiftyOne
    dataset_name: test
    # if you want to manually provide a different model name to be displayed in FiftyOne
    model_display_names: ["test_model"]
    # whether to launch the app from the script (True), or from ipython (and have finer control over the outputs)
    launch_app_from_script: false
    remote: true # for LAI, must be False
    address: 127.0.0.1 # ip to launch the app on.
    port: 5151 # port to launch the app on.

callbacks:
  anneal_weight:
    attr_name: total_unsupervised_importance
    init_val: 0.0
    increase_factor: 0.01
    final_val: 1.0
    freeze_until_epoch: 0

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
